### PR TITLE
Greek Language Update

### PR DESCRIPTION
**Pull request by MariosMpalas**
Small corrections on the translated file.

### CODE REVIEW

**Comment by Armin2208** [comment]
thanks buddy

**Comment by Spiritreader** [comment]
you forgot to merge lol

**Review by Spiritreader — APPROVED** [review]

**Comment by Armin2208** [comment]
> you forgot to merge lol

no GitHub forgot it

**Comment by MariosMpalas** [comment]
I saw a new entry in 10.3.0.10 beta version that doesn't exist in Resources.gr.resx. It says Accent color for taskbar and Windows borders. My question is. Will I have to translate the whole resources.resx file all over again each time a new entry is added or all language files (like resources.el-gr.resx) are being updated with the new entries for translators?

**Comment by Spiritreader** [comment]
Yes I had to rename the file to el-gr because wpf was really pedantic about the country code. You'll only have to update that file from now on

**Comment by MariosMpalas** [comment]
I can't find AutoDarkModeConfig directory. Have you put language files somewhere else?

**Comment by Spiritreader** [comment]
The project you're looking for is now AutoDarkModeLib as ongoing refactoring effort for the new features.

**Comment by MariosMpalas** [comment]
Ok, I found it. But I can't find the new additions in resources.el-gr.resx. Will they be added later? Also will every new addition be added at the last lite or somewhere inside the file?

**Comment by Spiritreader** [comment]
> Ok, I found it. But I can't find the new additions in resources.el-gr.resx. Will they be added later? Also will every new addition be added at the last lite or somewhere inside the file?

you'll have to copy over the new strings from the Resources.resx file

**Pull request merged**
